services:
  postgres:
    image: postgres:16
    container_name: dawker_db
    environment:
      POSTGRES_DB: dawker
      POSTGRES_USER: dawker_user
      POSTGRES_PASSWORD: dawker_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dawker_user -d dawker"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

